### ISSUE TITLE
[FEATURE] Plan views storage

### ISSUE THREAD

**Issue by ymarcon** [EPFL-ENAC/eesd-mast#16]
@mchaindl In the current implementation, the plan views are stored within the test files. I have the feeling that they should be separated, just like the 3d models files that are not with the test files. Is that correct?

**Comment by mchaindl** [comment]
@ymarcon It is not necessary to store the plan views (not necessary to include them for downloading). Instead, the plan views should be shown right below the picture of the building. Here is an example:

![image](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/721e79ed-c5f7-4b2a-8571-7a6bc541b6a2)

Regarding the 3D models, they will not be here anymore because now we will have another route for the 3D models. Therefore, in the details of the experimental results of each building, we should now have only "Details", "Test Results", "Files" (without including the 3D model and Period and DG evolution folders anymore), and "References".

**Comment by ymarcon** [comment]
Yes but to be shown, they need to be stored somewhere in the backend database. I understand from your answer that they are separated from the test files.

**Comment by mchaindl** [comment]
@ymarcon Yes, the plan views are separated from the test files.
