### ISSUE TITLE
[Feat/Design] Overview tab: Which plots need to be viewed simultaneously ?

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/eesd-mast#22]
- [x] Replace menu bar "Key Features" "Vulnerabiltiy" with a toggl on top of the selectors, "Show Vulnerability Plots"

Currently the "Key features" parallel coords plots can be viewed alternatively with the "Vulnerability" plots. Is that ok @mchaindl that they are not visible simultaneously ? Currently (note the text cut in the donut plots) : 
<img width="1527" alt="Screenshot 2024-05-16 at 09 35 11" src="https://github.com/EPFL-ENAC/eesd-mast/assets/18381609/867d5655-ff93-4ff6-b4d0-a83cba29f130">

The alternative is to do something closer to your initial design - with the Vulnerability plots apppearing in a right menu, in addition the rest, rather than instead - this is not feasible currently because of the left-menu (Resources) taking space too, but if that is removed (see #21), it should be do-able in a clean way. 

Let us know what you think @mchaindl - this thread should help us iterate on this tab's design ! Current

**Comment by mchaindl** [comment]
@charlottegiseleweil Yes, I think it is okay if they are not shown simultaneously. However, I would like to try to highlight the "Vulnerability" section a little bit more to push the user to look at it (because this analysis is one of the nice things about this database).

I'm not sure of the benefit of having the "Resources" tab on the left-menu. If we take it out we would have to have the welcome message somewhere (it could be like an info icon (
![image](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/0063be74-9c13-436b-a49b-42f73cebe571)
) that if the mouse is positioned over it the message is displayed)
