### ISSUE TITLE
Welcome message 

### ISSUE THREAD

**Issue by charlottegiseleweil** [EPFL-ENAC/eesd-mast#33]
- [ ] Add contact details
- [ ] Add "how to cite"

**Comment by mchaindl** [comment]
I also added an idea (https://github.com/EPFL-ENAC/eesd-mast/issues/31) on how we can put a banner at the end of the "Database Overview" page to manage the "How to cite" issue. Mainly because if we leave it only in the welcome pop-up message and the user does not remove the cookies, then he will not see the message again.

**Comment by mchaindl** [comment]
I moved this to https://github.com/EPFL-ENAC/eesd-mast/issues/31
