### ISSUE TITLE
Website address

### ISSUE THREAD

**Issue by ymarcon** [EPFL-ENAC/eesd-mast#44]
What will be the final website address? I propose https://mast.epfl.ch to keep things simple but you can choose another one.

**Comment by mchaindl** [comment]
We need to think about it because at ETH there exists a testing machine called MAST (Multi-Axis Subassemblage Testing), and I am not sure about this abbreviation overlap. Another option could be: https://urmshaketests.epfl.ch or https://urmshake-db.epfl.ch (something like that). Anyway, I will discuss it here in the lab first. Thanks

**Comment by ymarcon** [comment]
Let me know when the website address is decided, I need it to prepare the deployment of the webapp in production (currently it is just in a test environment).

**Comment by mchaindl** [comment]
@ymarcon According to what we discussed within the EESD group, the address will be https://masonrydb.epfl.ch. That way in the future, if we merge our databases, we will add the type of database in the address (for example: https://masonrydb.epfl.ch/shaketable)

**Comment by ymarcon** [comment]
Address is registered in the EPFL DNS
