### ISSUE TITLE
Filter more than one feature for the same donut chart

### ISSUE THREAD

**Issue by ymarcon** [EPFL-ENAC/eesd-mast#45]
Would be possible to filter more than one feature for the same donut chart?. Or at least show the selected feature in the corresponding color and all the rest in a lightgrey color?

![335499010-652cd965-9046-43f5-a544-b69168f262ba](https://github.com/EPFL-ENAC/eesd-mast/assets/2581149/9dd5e6d7-638a-44cf-82e5-b7097b711dcd)

**Comment by charlottegiseleweil** [comment]
@mchaindl these would really complicate the UX of the Overview tb which aims to remiain simple - the VBuildings tab is designed for usch combined finer filtering options - so the behavior requested is already available but from another tab. but two questions to ensure we understand well your request: 

(1) Do you want to change the "look" of the filtered donu (i.e. currently, when filtering for a category, all plot recaclulate, but what's you're showing in our screenshot is that the filtered-out categories still appear in grey). Is that intentional and do you want this important change of design ?

(2) Can you describe in detail what happens when filtering on several donut charts, over several categories ? Because it will be splitting each category in smaller amounts, you realize this will make it much less intuitive to read ? 

Happy to discuss in person if better !

**Comment by mchaindl** [comment]
@charlottegiseleweil Here are the answers:
(1) Yes I want the other categories to still appear in a lightgrey color when selecting one of the categories in a donut. Indeed it is very important to allow the user to filter more than one category for the same donut, because then the vulnerability analysis (and also the connections that are shown in the parallel plot) makes complete sense and allows to have a much better understanding of the behavior of the buildings in the database.

(2) For example, allowing the multiple filtering in the donut charts, will allow us to immediately see the differences between buildings clustered in different typologies. For example, in this type of building, it is important to see the difference between buildings of up to two storeys with taller buildings. The same for looking into the effect of the scale of the test. So the important effect of doing this will be translated into the vulnerability analysis (also in the parallel plot but with less level of importance)

**Comment by ymarcon** [comment]
Let's imagine this scenario:
1. user selects Clay =>
  * Masonry mat: Clay slice is colored, other slices are grey
  * Diaph mat: each slice that is related to the buildings in Clay are split: Timber-clay (colored), Timber-others (grey), RC-clay (colored), RC-others etc.
2. users selects Stone =>  
  * Masonry mat: Clay slice is colored, Stone is colored, other slices are grey
  * Diaph mat: Timber-clay (colored), Timber-stone (colored), Timber-others (grey), RC etc.
3. users selects a diaph mat => what is the expected logic??

=> it is getting very complicated

**Comment by mchaindl** [comment]
The expected outcome from these multiple selections is to see the changes in the fragility curves do to the several characteristics that the buildings can have, considering that buildings can be clustered in several typologies that may include more than one aspect of the same donut chart. Then it also allows the user to see in a much faster way the differences between the fragility curves generated.

Is it the part of the vulnerability curves in correspondence to these filters what is complicating this?

**Comment by charlottegiseleweil** [comment]
Thanks for the clarifications @mchaindl !

We just re-discussed this in depth and although, we still don't really recommend it, because the UX will be less intuitive, with each category of the donut chart being then split in 2 (Selected/unselected greyed out), we have analysed carefully what it would take to code this : 
It would require modifying the behavior of the data viz library when selecting categories to highlight vs. grey out unsleected ones - and consequently modify the backend to filter out (with "OR" filters within one donut chart sleection and "AND" filters across donut charts). 
This is approx 1-2 days of work, and the hours remaining on this project do not allow us to implement this significant new feature so close to the end - Unfortunately, as the project finishes at the end of the month (week!) and this feture request came too late to be prioritized. Now this week, we certainly should focus on the final deployment etc. 

But we're of course available to further discuss if a quick in-between can be found ! And if this feature is really absolutely key to you, we can try to find a solution...

In the meantime, I let this issue open in the repository, so the suggestion remains for future improvement.

**Comment by mchaindl** [comment]
@charlottegiseleweil Thanks for the answer and discussion, I understand the additional complications that this could bring, however in a later version it would be very helpful to have it because the vulnerability analysis is one of the most useful tools of the database.
Thinking on our schedule and time remaining, I think for the moment is okay if we manage to show all categories of the donut charts with the selected only in the corresponding highlighted color and the rest in lightgray (as shown in the schemes that I provided but without the ability to select more than one feature)
By the way, does it help if we consider the multiple feature selection only for the Masonry Material chart?

**Comment by charlottegiseleweil** [comment]
thanks for your reply ! 
It's not simpler to do the feature for 1 chat only, as it requires the same logic/re-design to do... Would you have a minute this morning ayntime before 11h30 to stop by and discuss prioritization ? @mchaindl

**Comment by ymarcon** [comment]
The fragilities chart is included in the buildings page filter, then multiple criteria can be applied now (including the "show model" filter).

![image](https://github.com/EPFL-ENAC/eesd-mast/assets/2581149/57341737-ed52-4cca-8934-7f72a89e4bd1)

**Comment by mchaindl** [comment]
@ymarcon Nice! Please just add a title for that plot, like in this image:
![image](https://github.com/EPFL-ENAC/eesd-mast/assets/80859197/e0c847b9-1297-44d6-8698-ee90cb988a62)

**Comment by ymarcon** [comment]
@mchaindl "based on filter selection" is quite obvious, then following the UX principles from @charlottegiseleweil it could be just "Vulnerability analysis".
BTW isn't it "Fragilities analysis" instead?

**Comment by mchaindl** [comment]
@ymarcon Yes I agree, "Vulnerability analysis" should be enough. Fragility Analysis or Vulnerability Analysis refers to the same. Vulnerability is more commonly used.
